image: registry.melroy.org/melroy/docker-images/gtk-cmake-ninja:trixie

stages:
  - test
  - build
  - release

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/libreweb-browser/${CI_COMMIT_TAG}"
  RELEASE_LINKS_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/releases/${CI_COMMIT_TAG}/assets/links"

include:
  - template: Security/SAST.gitlab-ci.yml

# Linux build template (deb only)
.build_template: &build_definition
  stage: build
  script:
    - ./scripts/build-lnx-prod.sh "DEB"
  artifacts:
    name: Packages
    expire_in: 4 weeks
    paths:
      - build_prod/libreweb-browser-*.deb

unit_test:
  stage: test
  script: ./scripts/run-tests.sh

sast:
  stage: test
  variables:
    SAST_EXCLUDED_PATHS: "lib"
    SAST_EXCLUDED_ANALYZERS: "bandit,brakeman,eslint,gosec,kubesec,nodejs-scan,phpcs-security-audit,pmd-apex,security-code-scan,sobelow,spotbugs"
    SEARCH_MAX_DEPTH: 3

doxygen:
  stage: build
  script:
    - ./scripts/build-docs.sh
  artifacts:
    name: Doxygen
    paths:
      - build_docs/docs/html/

# Build trixie (deb + rpm + source archive)
build:trixie:
  stage: build
  script:
    - ./scripts/build-lnx-prod.sh "TGZ;DEB;RPM"
    - ./scripts/create-source-archive.sh
  artifacts:
    name: Packages
    expire_in: 4 weeks
    paths:
      - build_prod/libreweb-browser-*.deb
      - build_prod/libreweb-browser-*.rpm
      - build_prod/libreweb-browser-*.tar.gz
      - build_prod/libreweb-browser-source-*.tar.gz

# Bookworm (debian)
build:bookworm:
  image: registry.melroy.org/melroy/docker-images/gtk-cmake-ninja:bookworm
  <<: *build_definition

# Forky (debian)
build:forky:
  image: registry.melroy.org/melroy/docker-images/gtk-cmake-ninja:forky
  <<: *build_definition

# Noble (ubuntu)
build:noble:
  image: registry.melroy.org/melroy/docker-images/gtk-cmake-ninja:noble
  <<: *build_definition

# Plucky (ubuntu)
build:plucky:
  image: registry.melroy.org/melroy/docker-images/gtk-cmake-ninja:plucky
  <<: *build_definition

static_code_analysis:
  stage: build
  script: ./scripts/cpp-check.sh

code_style_guidelines:
  stage: build
  script: ./scripts/check-format.sh

# Upload artifacts & Create new release
upload_and_release:
  stage: release
  image: curlimages/curl:latest
  rules:
    - if: $CI_PROJECT_NAMESPACE == "libreweb" && $CI_COMMIT_TAG
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN"
      --upload-file build_prod/libreweb-browser-v${CI_COMMIT_TAG}.deb
      ${PACKAGE_REGISTRY_URL}/libreweb-browser-v${CI_COMMIT_TAG}.deb'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN"
       --upload-file build_prod/libreweb-browser-v${CI_COMMIT_TAG}.rpm
      ${PACKAGE_REGISTRY_URL}/libreweb-browser-v${CI_COMMIT_TAG}.rpm'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN"
      --upload-file build_prod/libreweb-browser-v${CI_COMMIT_TAG}.tar.gz
      ${PACKAGE_REGISTRY_URL}/libreweb-browser-v${CI_COMMIT_TAG}.tar.gz'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN"
      --upload-file build_prod/libreweb-browser-source-v${CI_COMMIT_TAG}.tar.gz
      ${PACKAGE_REGISTRY_URL}/libreweb-browser-source-v${CI_COMMIT_TAG}.tar.gz'

    - 'curl --request POST 
      --header "JOB-TOKEN: $CI_JOB_TOKEN"
      --header "Content-Type: application/json"
      --data "{\"name\":\"LibreWeb Browser (Compressed binary)\",\"url\":\"${PACKAGE_REGISTRY_URL}/libreweb-browser-v${CI_COMMIT_TAG}.tar.gz\",\"link_type\":\"package\"}"
      ${RELEASE_LINKS_URL}'
    - 'curl --request POST
      --header "JOB-TOKEN: $CI_JOB_TOKEN"
      --header "Content-Type: application/json"
      --data "{\"name\":\"LibreWeb Browser (Fedora/openSUSE/CentOS)\",\"url\":\"${PACKAGE_REGISTRY_URL}/libreweb-browser-v${CI_COMMIT_TAG}.rpm\",\"link_type\":\"package\"}"
      ${RELEASE_LINKS_URL}'
    - 'curl --request POST
      --header "JOB-TOKEN: $CI_JOB_TOKEN"
      --header "Content-Type: application/json"
      --data "{\"name\":\"LibreWeb Browser (Debian/Ubuntu/Linux Mint)\",\"url\":\"${PACKAGE_REGISTRY_URL}/libreweb-browser-v${CI_COMMIT_TAG}.deb\",\"link_type\":\"package\"}"
      ${RELEASE_LINKS_URL}'
    - 'curl --request POST
      --header "JOB-TOKEN: $CI_JOB_TOKEN"
      --header "Content-Type: application/json"
      --data "{\"name\":\"LibreWeb Browser Source Code Archive (tar.gz)\",\"url\":\"${PACKAGE_REGISTRY_URL}/libreweb-browser-source-v${CI_COMMIT_TAG}.tar.gz\",\"link_type\":\"package\"}"
      ${RELEASE_LINKS_URL}'

# TODO: look into: https://docs.gitlab.com/cli/release/upload/
